2018-07-17 16:25:14,622 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-17 16:25:14,622 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-17 16:25:14,832 [utils:execute] [DEBUG]- (0.010) SHOW FULL TABLES; args=None
2018-07-17 16:25:14,862 [utils:execute] [DEBUG]- (0.020) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-07-17 16:25:22,703 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 179
2018-07-17 16:25:23,381 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2018-07-17 16:25:23,388 [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 3066
2018-07-17 16:44:15,349 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-17 16:44:15,349 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-17 16:44:15,410 [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2018-07-17 16:44:15,410 [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-07-17 16:44:21,056 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 179
2018-07-17 16:50:08,154 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-17 16:50:08,154 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-17 16:50:08,214 [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2018-07-17 16:50:08,214 [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-07-17 16:50:13,825 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 179
2018-07-17 16:50:16,707 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 179
2018-07-17 16:50:21,484 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 179
2018-07-17 16:50:26,944 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 179
2018-07-17 16:53:33,744 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 179
2018-07-18 15:12:02,845 [utils:execute] [DEBUG]- (0.003) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-18 15:12:02,861 [utils:execute] [DEBUG]- (0.002) SELECT VERSION(); args=None
2018-07-18 15:12:03,036 [utils:execute] [DEBUG]- (0.062) SHOW FULL TABLES; args=None
2018-07-18 15:12:03,059 [utils:execute] [DEBUG]- (0.020) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-07-18 15:12:03,075 [utils:execute] [DEBUG]- (0.012) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'administrator'; args=(u'administrator',)
2018-07-18 15:12:32,144 [utils:execute] [DEBUG]- (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'administrator'; args=(u'administrator',)
2018-07-18 15:12:59,637 [utils:execute] [DEBUG]- (0.005) INSERT INTO `auth_user` (`password`, `last_login`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`) VALUES ('pbkdf2_sha256$36000$GSU9iwBuEZEa$NjL+R06ZTDRo/8PnmoWQFpsAH+0jFkU/9sktVd+Vgy8=', NULL, 1, 'administrator', '', '', 'tysnad@163.com', 1, 1, '2018-07-18 07:12:59'); args=[u'pbkdf2_sha256$36000$GSU9iwBuEZEa$NjL+R06ZTDRo/8PnmoWQFpsAH+0jFkU/9sktVd+Vgy8=', None, True, u'administrator', u'', u'', u'tysnad@163.com', True, True, u'2018-07-18 07:12:59']
2018-07-18 15:17:52,440 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-18 15:17:52,441 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-18 15:19:35,898 [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-18 15:19:35,898 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-18 15:19:35,959 [utils:execute] [DEBUG]- (0.009) SHOW FULL TABLES; args=None
2018-07-18 15:19:35,963 [utils:execute] [DEBUG]- (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-07-18 15:19:45,141 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 179
2018-07-18 15:19:46,108 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
2018-07-18 15:19:46,125 [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 3066
2018-07-18 15:28:52,615 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 179
2018-07-27 17:24:24,473 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-27 17:24:24,523 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-27 17:25:13,999 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-27 17:25:13,999 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-27 17:25:14,121 [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2018-07-27 17:25:14,131 [utils:execute] [DEBUG]- (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-07-27 17:25:17,931 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 527
2018-07-27 17:25:19,482 [basehttp:log_message] [INFO]- "GET /static/js/app.c4bf9b84687a4dc69f22.js HTTP/1.1" 200 12484
2018-07-27 17:25:19,482 [basehttp:log_message] [INFO]- "GET /static/js/manifest.3ad1d5771e9b13dbdad2.js HTTP/1.1" 200 858
2018-07-27 17:25:19,500 [basehttp:log_message] [INFO]- "GET /static/js/vendor.c507d8e94b79097c43c1.js HTTP/1.1" 200 142351
2018-07-27 17:25:19,503 [basehttp:log_message] [INFO]- "GET /static/css/app.e02639ca7fcb9dd2d8afda2b9a74394b.css HTTP/1.1" 200 225326
2018-07-27 17:25:19,648 [basehttp:log_message] [INFO]- "GET /static/img/defalut.252b00d.jpg HTTP/1.1" 200 43352
2018-07-27 17:25:29,155 [basehttp:log_message] [WARNING]- "GET /media/uploads/blog/images HTTP/1.1" 404 1783
2018-07-27 17:25:31,621 [basehttp:log_message] [WARNING]- "GET /media/uploads/blog/images HTTP/1.1" 404 1783
2018-07-27 17:25:40,062 [basehttp:log_message] [WARNING]- "GET /media/uploads/blog/images HTTP/1.1" 404 1783
2018-07-27 17:27:25,230 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-27 17:27:25,230 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-27 17:27:25,290 [utils:execute] [DEBUG]- (0.000) SHOW FULL TABLES; args=None
2018-07-27 17:27:25,301 [utils:execute] [DEBUG]- (0.010) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
2018-07-27 17:27:28,306 [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 527
2018-07-27 17:27:31,075 [basehttp:log_message] [INFO]- "GET /admin HTTP/1.1" 301 0
2018-07-27 17:27:31,118 [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
2018-07-27 17:27:31,164 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003912EB8>>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000000039EE358>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003913FD0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000000039EE208>, u'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>}, {}, {'username': u'', 'app_path': u'/admin/login/?next=/admin/', 'available_apps': [], 'site_name': '127.0.0.1:8000', 'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'title': u'\\u767b\\u5f55', 'site_header': u'Django \\u7ba1\\u7406', 'site': <django.contrib.sites.requests.RequestSite object at 0x00000000039EE3C8>, 'next': u'/admin/', 'site_title': u'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458', u'LANGUAGE_CODE': 'zh-hans', 'has_permission': False, 'site_url': '/', u'LANGUAGE_BIDI': False, u'view': <django.contrib.auth.views.LoginView object at 0x00000000038F40F0>}]"
2018-07-27 17:27:31,447 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003912EB8>>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000000039EE358>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003913FD0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000000039EE208>, u'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>}, {}, {'username': u'', 'app_path': u'/admin/login/?next=/admin/', 'available_apps': [], 'site_name': '127.0.0.1:8000', 'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'title': u'\\u767b\\u5f55', 'site_header': u'Django \\u7ba1\\u7406', 'site': <django.contrib.sites.requests.RequestSite object at 0x00000000039EE3C8>, 'next': u'/admin/', 'site_title': u'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458', u'LANGUAGE_CODE': 'zh-hans', 'has_permission': False, 'site_url': '/', u'LANGUAGE_BIDI': False, u'view': <django.contrib.auth.views.LoginView object at 0x00000000038F40F0>}]"
2018-07-27 17:27:31,467 [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1652
2018-07-27 17:27:31,930 [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 302 0
2018-07-27 17:27:31,964 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003A603C8>>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000000038B3B38>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003AC1BA8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000000039EE5F8>, u'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>}, {}, {'username': u'', 'app_path': u'/admin/login/?next=/admin/', 'available_apps': [], 'site_name': '127.0.0.1:8000', 'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'title': u'\\u767b\\u5f55', 'site_header': u'Django \\u7ba1\\u7406', 'site': <django.contrib.sites.requests.RequestSite object at 0x00000000038B3F60>, 'next': u'/admin/', 'site_title': u'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458', u'LANGUAGE_CODE': 'zh-hans', 'has_permission': False, 'site_url': '/', u'LANGUAGE_BIDI': False, u'view': <django.contrib.auth.views.LoginView object at 0x00000000038B3BA8>}]"
2018-07-27 17:27:31,969 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000003A603C8>>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000000038B3B38>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003AC1BA8>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00000000039EE5F8>, u'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>}, {}, {'username': u'', 'app_path': u'/admin/login/?next=/admin/', 'available_apps': [], 'site_name': '127.0.0.1:8000', 'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'title': u'\\u767b\\u5f55', 'site_header': u'Django \\u7ba1\\u7406', 'site': <django.contrib.sites.requests.RequestSite object at 0x00000000038B3F60>, 'next': u'/admin/', 'site_title': u'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458', u'LANGUAGE_CODE': 'zh-hans', 'has_permission': False, 'site_url': '/', u'LANGUAGE_BIDI': False, u'view': <django.contrib.auth.views.LoginView object at 0x00000000038B3BA8>}]"
2018-07-27 17:27:31,990 [basehttp:log_message] [INFO]- "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1652
2018-07-27 17:27:32,164 [basehttp:log_message] [INFO]- "GET /static/admin/css/base.css HTTP/1.1" 200 16066
2018-07-27 17:27:32,165 [basehttp:log_message] [INFO]- "GET /static/admin/css/login.css HTTP/1.1" 200 1203
2018-07-27 17:27:32,177 [basehttp:log_message] [INFO]- "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
2018-07-27 17:27:32,203 [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
2018-07-27 17:27:32,211 [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
2018-07-27 17:27:34,061 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-27 17:27:34,062 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-27 17:27:34,078 [utils:execute] [DEBUG]- (0.012) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`username` = 'a783525'; args=(u'a783525',)
2018-07-27 17:27:34,130 [utils:execute] [DEBUG]- (0.004) SELECT (1) AS `a` FROM `django_session` WHERE `django_session`.`session_key` = 'tc91rslop0tw701t40ku7814ezz1m8lz' LIMIT 1; args=(u'tc91rslop0tw701t40ku7814ezz1m8lz',)
2018-07-27 17:27:34,134 [utils:execute] [DEBUG]- (0.003) INSERT INTO `django_session` (`session_key`, `session_data`, `expire_date`) VALUES ('tc91rslop0tw701t40ku7814ezz1m8lz', 'YzBkZTBhMTdiOWU2MGNjOTkxYTJlYjkwMDQ5MTRhYjE5NmZlMGIzOTp7fQ==', '2018-08-10 17:27:34'); args=(u'tc91rslop0tw701t40ku7814ezz1m8lz', u'YzBkZTBhMTdiOWU2MGNjOTkxYTJlYjkwMDQ5MTRhYjE5NmZlMGIzOTp7fQ==', u'2018-08-10 17:27:34')
2018-07-27 17:27:34,160 [utils:execute] [DEBUG]- (0.003) UPDATE `auth_user` SET `last_login` = '2018-07-27 17:27:34' WHERE `auth_user`.`id` = 2; args=(u'2018-07-27 17:27:34', 2)
2018-07-27 17:27:34,178 [utils:execute] [DEBUG]- (0.002) UPDATE `django_session` SET `session_data` = 'M2NkOTk0NWZhNThkOTUyNjExMGQ4ZGE0NzA2ZWQ1NjU4NWNiYjJlZjp7Il9hdXRoX3VzZXJfaGFzaCI6ImI4NTk4YWNjY2FlOTc4N2I0ZjI3MTVlODM2ODkwOWQyY2ExZjk1MDYiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIyIn0=', `expire_date` = '2018-08-10 17:27:34' WHERE `django_session`.`session_key` = 'tc91rslop0tw701t40ku7814ezz1m8lz'; args=(u'M2NkOTk0NWZhNThkOTUyNjExMGQ4ZGE0NzA2ZWQ1NjU4NWNiYjJlZjp7Il9hdXRoX3VzZXJfaGFzaCI6ImI4NTk4YWNjY2FlOTc4N2I0ZjI3MTVlODM2ODkwOWQyY2ExZjk1MDYiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaWQiOiIyIn0=', u'2018-08-10 17:27:34', u'tc91rslop0tw701t40ku7814ezz1m8lz')
2018-07-27 17:27:34,190 [basehttp:log_message] [INFO]- "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
2018-07-27 17:27:34,204 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-27 17:27:34,207 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-27 17:27:34,211 [utils:execute] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'tc91rslop0tw701t40ku7814ezz1m8lz' AND `django_session`.`expire_date` > '2018-07-27 17:27:34'); args=('tc91rslop0tw701t40ku7814ezz1m8lz', u'2018-07-27 17:27:34')
2018-07-27 17:27:34,214 [utils:execute] [DEBUG]- (0.000) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 2; args=(2,)
2018-07-27 17:27:34,237 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x00000000038BA518>>, 'user': <SimpleLazyObject: <User: a783525>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003AC14E0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003A4B048>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django \\u7ba1\\u7406', 'available_apps': [{'app_url': u'/admin/myweb/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/articleclassify/', 'object_name': 'ArticleClassify', 'name': u'Article classifys', 'add_url': u'/admin/myweb/articleclassify/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/article/', 'object_name': 'Article', 'name': u'Articles', 'add_url': u'/admin/myweb/article/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/myweb/tag/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/usermessage/', 'object_name': 'UserMessage', 'name': u'User messages', 'add_url': u'/admin/myweb/usermessage/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/myweb/user/add/'}], 'has_module_perms': True, 'name': 'Myweb', 'app_label': 'myweb'}, {'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'\\u7528\\u6237', 'add_url': u'/admin/auth/user/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'\\u7ec4', 'add_url': u'/admin/auth/group/add/'}], 'has_module_perms': True, 'name': u'\\u8ba4\\u8bc1\\u548c\\u6388\\u6743', 'app_label': 'auth'}], 'site_title': u'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458', 'title': u'\\u7ad9\\u70b9\\u7ba1\\u7406', 'has_permission': True, 'app_list': [{'app_url': u'/admin/myweb/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/articleclassify/', 'object_name': 'ArticleClassify', 'name': u'Article classifys', 'add_url': u'/admin/myweb/articleclassify/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/article/', 'object_name': 'Article', 'name': u'Articles', 'add_url': u'/admin/myweb/article/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/myweb/tag/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/usermessage/', 'object_name': 'UserMessage', 'name': u'User messages', 'add_url': u'/admin/myweb/usermessage/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/myweb/user/add/'}], 'has_module_perms': True, 'name': 'Myweb', 'app_label': 'myweb'}, {'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'\\u7528\\u6237', 'add_url': u'/admin/auth/user/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'\\u7ec4', 'add_url': u'/admin/auth/group/add/'}], 'has_module_perms': True, 'name': u'\\u8ba4\\u8bc1\\u548c\\u6388\\u6743', 'app_label': 'auth'}], u'LANGUAGE_CODE': 'zh-hans', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
2018-07-27 17:27:34,243 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x00000000038BA518>>, 'user': <SimpleLazyObject: <User: a783525>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x0000000003AC14E0>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003A4B048>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django \\u7ba1\\u7406', 'available_apps': [{'app_url': u'/admin/myweb/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/articleclassify/', 'object_name': 'ArticleClassify', 'name': u'Article classifys', 'add_url': u'/admin/myweb/articleclassify/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/article/', 'object_name': 'Article', 'name': u'Articles', 'add_url': u'/admin/myweb/article/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/myweb/tag/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/usermessage/', 'object_name': 'UserMessage', 'name': u'User messages', 'add_url': u'/admin/myweb/usermessage/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/myweb/user/add/'}], 'has_module_perms': True, 'name': 'Myweb', 'app_label': 'myweb'}, {'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'\\u7528\\u6237', 'add_url': u'/admin/auth/user/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'\\u7ec4', 'add_url': u'/admin/auth/group/add/'}], 'has_module_perms': True, 'name': u'\\u8ba4\\u8bc1\\u548c\\u6388\\u6743', 'app_label': 'auth'}], 'site_title': u'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458', 'title': u'\\u7ad9\\u70b9\\u7ba1\\u7406', 'has_permission': True, 'app_list': [{'app_url': u'/admin/myweb/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/articleclassify/', 'object_name': 'ArticleClassify', 'name': u'Article classifys', 'add_url': u'/admin/myweb/articleclassify/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/article/', 'object_name': 'Article', 'name': u'Articles', 'add_url': u'/admin/myweb/article/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/myweb/tag/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/usermessage/', 'object_name': 'UserMessage', 'name': u'User messages', 'add_url': u'/admin/myweb/usermessage/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/myweb/user/add/'}], 'has_module_perms': True, 'name': 'Myweb', 'app_label': 'myweb'}, {'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'\\u7528\\u6237', 'add_url': u'/admin/auth/user/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'\\u7ec4', 'add_url': u'/admin/auth/group/add/'}], 'has_module_perms': True, 'name': u'\\u8ba4\\u8bc1\\u548c\\u6388\\u6743', 'app_label': 'auth'}], u'LANGUAGE_CODE': 'zh-hans', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
2018-07-27 17:27:34,273 [utils:execute] [DEBUG]- (0.014) SELECT `django_admin_log`.`id`, `django_admin_log`.`action_time`, `django_admin_log`.`user_id`, `django_admin_log`.`content_type_id`, `django_admin_log`.`object_id`, `django_admin_log`.`object_repr`, `django_admin_log`.`action_flag`, `django_admin_log`.`change_message`, `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_admin_log` INNER JOIN `auth_user` ON (`django_admin_log`.`user_id` = `auth_user`.`id`) LEFT OUTER JOIN `django_content_type` ON (`django_admin_log`.`content_type_id` = `django_content_type`.`id`) WHERE `django_admin_log`.`user_id` = 2 ORDER BY `django_admin_log`.`action_time` DESC LIMIT 10; args=(2,)
2018-07-27 17:27:34,279 [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 6288
2018-07-27 17:27:34,400 [basehttp:log_message] [INFO]- "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
2018-07-27 17:27:34,466 [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
2018-07-27 17:27:34,470 [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
2018-07-27 17:27:34,480 [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
2018-07-27 17:27:38,046 [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-27 17:27:38,048 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-27 17:27:38,055 [utils:execute] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'tc91rslop0tw701t40ku7814ezz1m8lz' AND `django_session`.`expire_date` > '2018-07-27 17:27:38'); args=('tc91rslop0tw701t40ku7814ezz1m8lz', u'2018-07-27 17:27:38')
2018-07-27 17:27:38,059 [utils:execute] [DEBUG]- (0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 2; args=(2,)
2018-07-27 17:27:38,072 [utils:execute] [DEBUG]- (0.010) SELECT COUNT(*) AS `__count` FROM `myweb_article`; args=()
2018-07-27 17:27:38,075 [utils:execute] [DEBUG]- (0.001) SELECT COUNT(*) AS `__count` FROM `myweb_article`; args=()
2018-07-27 17:27:38,079 [utils:execute] [DEBUG]- (0.000) SELECT `myweb_article`.`id`, `myweb_article`.`title`, `myweb_article`.`author_id`, `myweb_article`.`classify_id`, `myweb_article`.`browse`, `myweb_article`.`status`, `myweb_article`.`update_time`, `myweb_article`.`create_time`, `myweb_article`.`content` FROM `myweb_article` ORDER BY `myweb_article`.`id` DESC; args=()
2018-07-27 17:27:38,098 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'errors' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [errors] in u'None'
2018-07-27 17:27:38,104 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'show' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [show] in u"[{'False': False, 'None': None, 'True': True, 'csrf_token': <SimpleLazyObject: <function _get_val at 0x0000000002B9F358>>}]"
2018-07-27 17:27:38,105 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_multipart' in template 'admin/change_list.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_multipart] in u'None'
2018-07-27 17:27:38,114 [basehttp:log_message] [INFO]- "GET /admin/myweb/article/ HTTP/1.1" 200 3053
2018-07-27 17:27:38,164 [basehttp:log_message] [INFO]- "GET /static/admin/css/changelists.css HTTP/1.1" 200 6170
2018-07-27 17:27:38,184 [basehttp:log_message] [INFO]- "GET /static/admin/js/core.js HTTP/1.1" 200 7976
2018-07-27 17:27:38,186 [utils:execute] [DEBUG]- (0.001) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-27 17:27:38,190 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-27 17:27:38,200 [basehttp:log_message] [INFO]- "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 363
2018-07-27 17:27:38,203 [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6591
2018-07-27 17:27:38,204 [utils:execute] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'tc91rslop0tw701t40ku7814ezz1m8lz' AND `django_session`.`expire_date` > '2018-07-27 17:27:38'); args=('tc91rslop0tw701t40ku7814ezz1m8lz', u'2018-07-27 17:27:38')
2018-07-27 17:27:38,207 [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.js HTTP/1.1" 200 6501
2018-07-27 17:27:38,211 [utils:execute] [DEBUG]- (0.002) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 2; args=(2,)
2018-07-27 17:27:38,220 [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7758
2018-07-27 17:27:38,227 [basehttp:log_message] [INFO]- "GET /static/admin/js/urlify.js HTTP/1.1" 200 8186
2018-07-27 17:27:38,239 [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1538
2018-07-27 17:27:38,247 [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 258648
2018-07-27 17:27:38,279 [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 128820
2018-07-27 17:27:38,329 [basehttp:log_message] [INFO]- "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
2018-07-27 17:27:42,134 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-27 17:27:42,135 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-27 17:27:42,144 [utils:execute] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'tc91rslop0tw701t40ku7814ezz1m8lz' AND `django_session`.`expire_date` > '2018-07-27 17:27:42'); args=('tc91rslop0tw701t40ku7814ezz1m8lz', u'2018-07-27 17:27:42')
2018-07-27 17:27:42,147 [utils:execute] [DEBUG]- (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 2; args=(2,)
2018-07-27 17:27:42,163 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x00000000038BA518>>, 'user': <SimpleLazyObject: <User: a783525>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00000000039EED68>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003AEBBA8>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django \\u7ba1\\u7406', 'available_apps': [{'app_url': u'/admin/myweb/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/articleclassify/', 'object_name': 'ArticleClassify', 'name': u'Article classifys', 'add_url': u'/admin/myweb/articleclassify/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/article/', 'object_name': 'Article', 'name': u'Articles', 'add_url': u'/admin/myweb/article/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/myweb/tag/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/usermessage/', 'object_name': 'UserMessage', 'name': u'User messages', 'add_url': u'/admin/myweb/usermessage/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/myweb/user/add/'}], 'has_module_perms': True, 'name': 'Myweb', 'app_label': 'myweb'}, {'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'\\u7528\\u6237', 'add_url': u'/admin/auth/user/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'\\u7ec4', 'add_url': u'/admin/auth/group/add/'}], 'has_module_perms': True, 'name': u'\\u8ba4\\u8bc1\\u548c\\u6388\\u6743', 'app_label': 'auth'}], 'site_title': u'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458', 'title': u'\\u7ad9\\u70b9\\u7ba1\\u7406', 'has_permission': True, 'app_list': [{'app_url': u'/admin/myweb/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/articleclassify/', 'object_name': 'ArticleClassify', 'name': u'Article classifys', 'add_url': u'/admin/myweb/articleclassify/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/article/', 'object_name': 'Article', 'name': u'Articles', 'add_url': u'/admin/myweb/article/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/myweb/tag/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/usermessage/', 'object_name': 'UserMessage', 'name': u'User messages', 'add_url': u'/admin/myweb/usermessage/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/myweb/user/add/'}], 'has_module_perms': True, 'name': 'Myweb', 'app_label': 'myweb'}, {'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'\\u7528\\u6237', 'add_url': u'/admin/auth/user/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'\\u7ec4', 'add_url': u'/admin/auth/group/add/'}], 'has_module_perms': True, 'name': u'\\u8ba4\\u8bc1\\u548c\\u6388\\u6743', 'app_label': 'auth'}], u'LANGUAGE_CODE': 'zh-hans', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
2018-07-27 17:27:42,167 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_popup] in u"[{'False': False, 'None': None, 'True': True}, {u'csrf_token': <SimpleLazyObject: <function _get_val at 0x00000000038BA518>>, 'user': <SimpleLazyObject: <User: a783525>>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00000000039EED68>, 'DEFAULT_MESSAGE_LEVELS': {'DEBUG': 10, 'INFO': 20, 'WARNING': 30, 'SUCCESS': 25, 'ERROR': 40}, 'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0000000003AEBBA8>, u'request': <WSGIRequest: GET '/admin/'>}, {}, {'site_header': u'Django \\u7ba1\\u7406', 'available_apps': [{'app_url': u'/admin/myweb/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/articleclassify/', 'object_name': 'ArticleClassify', 'name': u'Article classifys', 'add_url': u'/admin/myweb/articleclassify/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/article/', 'object_name': 'Article', 'name': u'Articles', 'add_url': u'/admin/myweb/article/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/myweb/tag/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/usermessage/', 'object_name': 'UserMessage', 'name': u'User messages', 'add_url': u'/admin/myweb/usermessage/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/myweb/user/add/'}], 'has_module_perms': True, 'name': 'Myweb', 'app_label': 'myweb'}, {'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'\\u7528\\u6237', 'add_url': u'/admin/auth/user/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'\\u7ec4', 'add_url': u'/admin/auth/group/add/'}], 'has_module_perms': True, 'name': u'\\u8ba4\\u8bc1\\u548c\\u6388\\u6743', 'app_label': 'auth'}], 'site_title': u'Django \\u7ad9\\u70b9\\u7ba1\\u7406\\u5458', 'title': u'\\u7ad9\\u70b9\\u7ba1\\u7406', 'has_permission': True, 'app_list': [{'app_url': u'/admin/myweb/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/articleclassify/', 'object_name': 'ArticleClassify', 'name': u'Article classifys', 'add_url': u'/admin/myweb/articleclassify/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/article/', 'object_name': 'Article', 'name': u'Articles', 'add_url': u'/admin/myweb/article/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/tag/', 'object_name': 'Tag', 'name': u'Tags', 'add_url': u'/admin/myweb/tag/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/usermessage/', 'object_name': 'UserMessage', 'name': u'User messages', 'add_url': u'/admin/myweb/usermessage/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/myweb/user/', 'object_name': 'User', 'name': u'Users', 'add_url': u'/admin/myweb/user/add/'}], 'has_module_perms': True, 'name': 'Myweb', 'app_label': 'myweb'}, {'app_url': u'/admin/auth/', 'models': [{'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/user/', 'object_name': 'User', 'name': u'\\u7528\\u6237', 'add_url': u'/admin/auth/user/add/'}, {'perms': {u'add': True, u'change': True, u'delete': True}, 'admin_url': u'/admin/auth/group/', 'object_name': 'Group', 'name': u'\\u7ec4', 'add_url': u'/admin/auth/group/add/'}], 'has_module_perms': True, 'name': u'\\u8ba4\\u8bc1\\u548c\\u6388\\u6743', 'app_label': 'auth'}], u'LANGUAGE_CODE': 'zh-hans', u'LANGUAGE_BIDI': False, 'site_url': '/'}]"
2018-07-27 17:27:42,178 [utils:execute] [DEBUG]- (0.001) SELECT `django_admin_log`.`id`, `django_admin_log`.`action_time`, `django_admin_log`.`user_id`, `django_admin_log`.`content_type_id`, `django_admin_log`.`object_id`, `django_admin_log`.`object_repr`, `django_admin_log`.`action_flag`, `django_admin_log`.`change_message`, `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined`, `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_admin_log` INNER JOIN `auth_user` ON (`django_admin_log`.`user_id` = `auth_user`.`id`) LEFT OUTER JOIN `django_content_type` ON (`django_admin_log`.`content_type_id` = `django_content_type`.`id`) WHERE `django_admin_log`.`user_id` = 2 ORDER BY `django_admin_log`.`action_time` DESC LIMIT 10; args=(2,)
2018-07-27 17:27:42,183 [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 6288
2018-07-27 17:27:51,671 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-27 17:27:51,671 [utils:execute] [DEBUG]- (0.000) SELECT VERSION(); args=None
2018-07-27 17:27:51,681 [utils:execute] [DEBUG]- (0.000) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'tc91rslop0tw701t40ku7814ezz1m8lz' AND `django_session`.`expire_date` > '2018-07-27 17:27:51'); args=('tc91rslop0tw701t40ku7814ezz1m8lz', u'2018-07-27 17:27:51')
2018-07-27 17:27:51,684 [utils:execute] [DEBUG]- (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 2; args=(2,)
2018-07-27 17:27:51,700 [utils:execute] [DEBUG]- (0.001) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'article' AND `django_content_type`.`app_label` = 'myweb'); args=('article', 'myweb')
2018-07-27 17:27:51,737 [utils:execute] [DEBUG]- (0.009) SELECT `myweb_user`.`id`, `myweb_user`.`name`, `myweb_user`.`password`, `myweb_user`.`message_id`, `myweb_user`.`update_time`, `myweb_user`.`create_time` FROM `myweb_user`; args=()
2018-07-27 17:27:51,747 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/myweb/user/add/\', u\'name\': \'author\', \'can_change_related\': True, \'can_add_related\': True, u\'model\': u\'user\', \'change_related_template_url\': u\'/admin/myweb/user/__fk__/change/\', u\'rendered_widget\': u\'<select name="author" required id="id_author">\\n  <option value="" selected>---------</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x0000000003C6B048>, <TextNode: u\'\\n    \'>]>}]'
2018-07-27 17:27:51,756 [utils:execute] [DEBUG]- (0.006) SELECT `myweb_tag`.`id`, `myweb_tag`.`name` FROM `myweb_tag`; args=()
2018-07-27 17:27:51,762 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'can_change_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_change_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/myweb/tag/add/\', u\'name\': \'tag\', \'can_add_related\': True, u\'model\': u\'tag\', u\'rendered_widget\': u\'<select name="tag" required multiple="multiple" id="id_tag">\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x0000000003C61C18>, <TextNode: u\'\\n    \'>]>}]'
2018-07-27 17:27:51,763 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/myweb/tag/add/\', u\'name\': \'tag\', \'can_add_related\': True, u\'model\': u\'tag\', u\'rendered_widget\': u\'<select name="tag" required multiple="multiple" id="id_tag">\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x0000000003C61C18>, <TextNode: u\'\\n    \'>]>}]'
2018-07-27 17:27:51,773 [utils:execute] [DEBUG]- (0.006) SELECT `myweb_articleclassify`.`id`, `myweb_articleclassify`.`name`, `myweb_articleclassify`.`parent_id` FROM `myweb_articleclassify`; args=()
2018-07-27 17:27:51,782 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'can_delete_related' in template 'admin/widgets/related_widget_wrapper.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [can_delete_related] in u'[{\'False\': False, \'None\': None, \'True\': True}, {u\'url_params\': u\'_to_field=id&_popup=1\', \'add_related_url\': u\'/admin/myweb/articleclassify/add/\', u\'name\': \'classify\', \'can_change_related\': True, \'can_add_related\': True, u\'model\': u\'article classify\', \'change_related_template_url\': u\'/admin/myweb/articleclassify/__fk__/change/\', u\'rendered_widget\': u\'<select name="classify" required id="id_classify">\\n  <option value="" selected>---------</option>\\n\\n</select>\'}, {\'block\': <Block Node: links. Contents: [<TextNode: u\'\\n        \'>, <django.template.defaulttags.SpacelessNode object at 0x0000000003C6B978>, <TextNode: u\'\\n    \'>]>}]'
2018-07-27 17:27:51,806 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'commands' in template 'ueditor.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [commands] in u"{'settings': {'toolbars': [['source', 'undo', 'redo', 'bold', 'italic', 'underline', 'forecolor', 'backcolor', 'superscript', 'subscript', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist', 'insertunorderedlist', 'blockquote', 'formatmatch', 'removeformat', 'autotypeset', 'inserttable', 'pasteplain', 'wordimage', 'searchreplace', 'map', 'preview', 'fullscreen'], ['insertcode', 'paragraph', 'fontfamily', 'fontsize', 'link', 'unlink', 'insertimage', 'insertvideo', 'attachment', 'emotion', 'date', 'time']], 'initialFrameWidth': 1000, 'initialFrameHeight': 300, 'serverUrl': '/ueditor/controller/?imagePathFormat=uploads%2Fblog%2Fimages&filePathFormat=uploads%2Fblog%2Ffiles'}, 'name': 'content', 'value': u'', 'id': 'id_content'}"
2018-07-27 17:27:51,809 [base:_resolve_lookup] [DEBUG]- Exception while resolving variable 'bindEvents' in template 'ueditor.html'.
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django-1.11.14-py2.7.egg\django\template\base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [bindEvents] in u"{'settings': {'toolbars': [['source', 'undo', 'redo', 'bold', 'italic', 'underline', 'forecolor', 'backcolor', 'superscript', 'subscript', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist', 'insertunorderedlist', 'blockquote', 'formatmatch', 'removeformat', 'autotypeset', 'inserttable', 'pasteplain', 'wordimage', 'searchreplace', 'map', 'preview', 'fullscreen'], ['insertcode', 'paragraph', 'fontfamily', 'fontsize', 'link', 'unlink', 'insertimage', 'insertvideo', 'attachment', 'emotion', 'date', 'time']], 'initialFrameWidth': 1000, 'initialFrameHeight': 300, 'serverUrl': '/ueditor/controller/?imagePathFormat=uploads%2Fblog%2Fimages&filePathFormat=uploads%2Fblog%2Ffiles'}, 'name': 'content', 'value': u'', 'id': 'id_content'}"
2018-07-27 17:27:51,818 [basehttp:log_message] [INFO]- "GET /admin/myweb/article/add/ HTTP/1.1" 200 10985
2018-07-27 17:27:51,871 [basehttp:log_message] [INFO]- "GET /static/admin/css/forms.css HTTP/1.1" 200 8173
2018-07-27 17:27:51,878 [utils:execute] [DEBUG]- (0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
2018-07-27 17:27:51,881 [utils:execute] [DEBUG]- (0.001) SELECT VERSION(); args=None
2018-07-27 17:27:51,885 [utils:execute] [DEBUG]- (0.001) SELECT `django_session`.`session_key`, `django_session`.`session_data`, `django_session`.`expire_date` FROM `django_session` WHERE (`django_session`.`session_key` = 'tc91rslop0tw701t40ku7814ezz1m8lz' AND `django_session`.`expire_date` > '2018-07-27 17:27:51'); args=('tc91rslop0tw701t40ku7814ezz1m8lz', u'2018-07-27 17:27:51')
2018-07-27 17:27:51,890 [utils:execute] [DEBUG]- (0.001) SELECT `auth_user`.`id`, `auth_user`.`password`, `auth_user`.`last_login`, `auth_user`.`is_superuser`, `auth_user`.`username`, `auth_user`.`first_name`, `auth_user`.`last_name`, `auth_user`.`email`, `auth_user`.`is_staff`, `auth_user`.`is_active`, `auth_user`.`date_joined` FROM `auth_user` WHERE `auth_user`.`id` = 2; args=(2,)
2018-07-27 17:27:51,898 [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 7758
2018-07-27 17:27:51,927 [basehttp:log_message] [INFO]- "GET /static/admin/js/calendar.js HTTP/1.1" 200 7790
2018-07-27 17:27:51,937 [basehttp:log_message] [INFO]- "GET /static/ueditor/ueditor.config.js HTTP/1.1" 200 20239
2018-07-27 17:27:51,940 [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 20529
2018-07-27 17:27:51,967 [basehttp:log_message] [INFO]- "GET /static/admin/css/widgets.css HTTP/1.1" 200 10340
2018-07-27 17:27:51,967 [basehttp:log_message] [INFO]- "GET /static/admin/js/change_form.js HTTP/1.1" 200 712
2018-07-27 17:27:51,970 [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 495
2018-07-27 17:27:51,970 [basehttp:log_message] [INFO]- "GET /static/ueditor/ueditor.all.min.js HTTP/1.1" 200 368515
2018-07-27 17:27:52,147 [basehttp:log_message] [INFO]- "GET /static/ueditor/lang/zh-cn/zh-cn.js HTTP/1.1" 200 30020
2018-07-27 17:27:52,161 [basehttp:log_message] [INFO]- "GET /static/ueditor/themes/default/css/ueditor.css HTTP/1.1" 200 45662
2018-07-27 17:27:52,190 [basehttp:log_message] [INFO]- "GET /ueditor/controller/?imagePathFormat=uploads%2Fblog%2Fimages&filePathFormat=uploads%2Fblog%2Ffiles&action=config&&noCache=1532683672182 HTTP/1.1" 200 2171
2018-07-27 17:27:52,263 [basehttp:log_message] [INFO]- "GET /static/ueditor/themes/default/images/scale.png HTTP/1.1" 200 167
2018-07-27 17:27:52,266 [basehttp:log_message] [INFO]- "GET /static/ueditor/themes/default/images/icons.png HTTP/1.1" 200 19694
2018-07-27 17:27:52,290 [basehttp:log_message] [INFO]- "GET /static/ueditor/themes/iframe.css HTTP/1.1" 200 42
2018-07-27 17:27:52,345 [basehttp:log_message] [INFO]- "GET /static/ueditor/third-party/codemirror/codemirror.css HTTP/1.1" 200 2992
2018-07-27 17:27:52,364 [basehttp:log_message] [INFO]- "GET /static/ueditor/third-party/codemirror/codemirror.js HTTP/1.1" 200 162186
2018-07-27 17:27:52,371 [basehttp:log_message] [INFO]- "GET /static/ueditor/third-party/zeroclipboard/ZeroClipboard.js HTTP/1.1" 200 44471
2018-07-27 17:27:52,418 [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
2018-07-27 17:27:52,418 [basehttp:log_message] [INFO]- "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
